language: generic

dist: xenial

before_deploy:
  - cp a.sh a_$TRAVIS_BUILD_NUMBER.sh

deploy:
  - provider: script
    script: python hello.py
    skip_cleanup: true
    on:
      condition: $(bash .travisci/check_file_changed.sh a.sh) = 0
      branch:
         - master
