language: generic

dist: xenial

deploy:
  - provider: script
    script: python hello.py
    skip_cleanup: true
    on:
      condition: $(bash check_file_changed.sh a.sh) = 1
      tags: false
      all_branches: true
